# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    #sciezka_do_skanow: '/var/www/html/skany/'
    sciezka_do_skanow: '%env(sciezka_do_skanow)%'
    sciezka_do_png: '%env(sciezka_do_png)%' #'/var/www/html/pisma/public/png/'
    sciezka_do_podgladuOdt: '%env(sciezka_do_podgladuOdt)%' #'/var/www/html/pisma/public/Odt_html/'
    sciezka_do_zarejestrowanych: '%env(sciezka_do_zarejestrowanych)%' #'/var/www/html/skanyZarejestrowane/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    #lista dostępnych implementacji:
    App\Service\PismoPrzetwarzanie\PpArgPracaRouter: ~
    App\Service\PismoPrzetwarzanie\PpArgPracaRouterRepo: ~
    App\Service\PismoPrzetwarzanie\PpArgPracaRouterRepoStopWatch: ~

    #konfiguracja zależności
    App\Service\PismoPrzetwarzanie\PismoPrzetwarzanieArgumentyInterface: '@App\Service\PismoPrzetwarzanie\PpArgPracaRouterRepoStopWatch'

    #jawne dopasowanie argumentu
    App\Service\PracaNaPlikach:
        arguments:
            $domyslnyFolderZplikami: '%sciezka_do_skanow%'

#ustawić również w .env.test.local:
#sciezka_do_podgladuOdt='??/??/pisma/tests/podgladDlaOdt/'